### ISSUE TITLE
com.adobe.acs.acs-aem-tools-bundle-livereload bundle fails on AEM 6.0 SP3

### ISSUE THREAD

**Issue by thedoc31** [Adobe-Consulting-Services/acs-aem-tools#154]
Attempting to install latest ACS Tools on AEM 6.0 SP3. During installation, I see the error at [0] appear in error.log.  The rest of the installation seems to proceed without issue.  This also occurs with 0.0.22, but does not when rolling back to 0.0.20.

org.osgi.framework.BundleException: Unresolved constraint in bundle com.adobe.acs.acs-aem-tools-bundle-livereload [432]: Unable to resolve 432.3: missing requirement [432.3] osgi.wiring.package; (&(osgi.wiring.package=io.netty.bootstrap)(version>=4.0.0)(!(version>=5.0.0)))
	at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:3980)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2043)
	at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:976)
	at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:963)
	at org.apache.sling.installer.core.impl.tasks.BundleStartTask.execute(BundleStartTask.java:93)
	at org.apache.sling.installer.core.impl.OsgiInstallerImpl.doExecuteTasks(OsgiInstallerImpl.java:847)
	at org.apache.sling.installer.core.impl.OsgiInstallerImpl.executeTasks(OsgiInstallerImpl.java:689)
	at org.apache.sling.installer.core.impl.OsgiInstallerImpl.run(OsgiInstallerImpl.java:265)
	at java.lang.Thread.run(Thread.java:745)
12.08.2016 17:10:16.526 *INFO* [OsgiInstallerImpl] org.apache.sling.installer.core.impl.tasks.BundleStartTask Could not start bundle com.adobe.acs.acs-aem-tools-bundle-livereload [432]. Reason: {}. Will retry.
org.osgi.framework.BundleException: Unresolved constraint in bundle com.adobe.acs.acs-aem-tools-bundle-livereload [432]: Unable to resolve 432.3: missing requirement [432.3] osgi.wiring.package; (&(osgi.wiring.package=io.netty.bootstrap)(version>=4.0.0)(!(version>=5.0.0)))
	at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:3980)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2043)
	at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:976)
	at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:963)
	at org.apache.sling.installer.core.impl.tasks.BundleStartTask.execute(BundleStartTask.java:93)
	at org.apache.sling.installer.core.impl.OsgiInstallerImpl.doExecuteTasks(OsgiInstallerImpl.java:847)
	at org.apache.sling.installer.core.impl.OsgiInstallerImpl.executeTasks(OsgiInstallerImpl.java:689)
	at org.apache.sling.installer.core.impl.OsgiInstallerImpl.run(OsgiInstallerImpl.java:265)
	at java.lang.Thread.run(Thread.java:745)

**Comment by justinedelson** [comment]
is the netty bundle installed?

**Comment by justinedelson** [comment]
Netty is required to use this feature. See http://adobe-consulting-services.github.io/acs-aem-tools/features/live-reload.html
