### ISSUE TITLE
Renovator does not support rep:CugPolicy and nt:file type of nodes

### ISSUE THREAD

**Issue by leoberliant** [Adobe-Consulting-Services/acs-aem-tools#235]
Renovation fails to copy/move nodes tree if one of the child nodes is nt:file or rep:CugPolicy

stuck trace:
`com.adobe.acs.commons.util.visitors.TraversalException: javax.jcr.RepositoryException: Type rep:CugPolicy is not supported at this time! at com.adobe.acs.commons.util.visitors.SimpleFilteringResourceVisitor.visitNodesInStack(SimpleFilteringResourceVisitor.java:129) at com.adobe.acs.commons.util.visitors.SimpleFilteringResourceVisitor.accept(SimpleFilteringResourceVisitor.java:109) at com.adobe.acs.commons.mcp.impl.processes.renovator.Renovator.identifyStructureFromRoot(Renovator.java:514) at com.adobe.acs.commons.mcp.impl.processes.renovator.Renovator.lambda$null$12(Renovator.java:485) at com.adobe.acs.commons.fam.impl.ActionManagerImpl.withResolver(ActionManagerImpl.java:200) at com.adobe.acs.commons.fam.impl.ActionManagerImpl.runActionAndLogErrors(ActionManagerImpl.java:167) at com.adobe.acs.commons.fam.impl.ActionManagerImpl.lambda$deferredWithResolver$0(ActionManagerImpl.java:159) at com.adobe.acs.commons.fam.impl.TimedRunnable.run(TimedRunnable.java:91) at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) at java.util.concurrent.FutureTask.run(FutureTask.java:266) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at java.lang.Thread.run(Thread.java:748) Caused by: javax.jcr.RepositoryException: Type rep:CugPolicy is not supported at this time! at com.adobe.acs.commons.mcp.impl.processes.renovator.Renovator.buildMoveNode(Renovator.java:569) at com.adobe.acs.commons.mcp.impl.processes.renovator.Renovator.buildMoveTree(Renovator.java:521) at com.adobe.acs.commons.mcp.impl.processes.renovator.Renovator.lambda$identifyStructureFromRoot$16(Renovator.java:512) at com.adobe.acs.commons.util.visitors.SimpleFilteringResourceVisitor.visitNodesInStack(SimpleFilteringResourceVisitor.java:126) ... 12 more`

and
`ERROR* [pool-40-thread-3] com.adobe.acs.commons.fam.impl.ActionManagerImpl Error in action Renovator: Publish mode none: Eval Struct (af1b88b9-df52-451c-a69f-c134a3e88d30)
com.adobe.acs.commons.util.visitors.TraversalException: javax.jcr.RepositoryException: Type nt:file is not supported at this time!`

**Comment by davidjgonzalez** [comment]
@badvision any quick thoughts on how to fix? it seems? that the you can move rep:cugPolicy if you move a parent node (maybe nt:hierarchyType, or whatever that restriction is there) ... seems like this error is coming in during the walk of the tree itself? Think we could just skip walking rep:CugPolicy? Would they still get copied over?
