### ISSUE TITLE
VLT-RCP Issues on AEM 6.5

### ISSUE THREAD

**Issue by normraby** [Adobe-Consulting-Services/acs-aem-tools#236]
Here is what we ran:
Go to http://qa-aem65-auth.corp.global:4502/etc/acs-tools/vlt-rcp.html
Click on Add Task
Set the Task Id to any name as long as it doesn’t match another defined task
Set the Source to http://aem-assets-sandbox1-auth.corp.global:4502/crx/server/crx.default/jcr:root/content/dam/maintenance
Provide a username / password for the source instance
Set the Destination of where the nodes need to be copied to. /content/dam/maintenance
Set Recursive to Yes
Leave update, Only newer, and No ordering set as No
I typically set the batch size to something small like 10
I typically set the Throttle to 5
Click Create New Task
Once it is saved and you are back at the list of Tasks you can click on the play button to start the task.

Here is what I saw in the error log when I ran it.
 
10.12.2021 13:22:47.102 *INFO* [Vault RCP Task - Norm1] org.apache.jackrabbit.vault.rcp.impl.RcpTaskImpl Starting repository copy task id=Norm1. From http://aem-assets-sandbox1-auth.corp.global:4502/crx/server/crx.default/jcr:root/content/dam/maintenance to /content/dam/maintenance.
10.12.2021 13:22:47.103 *INFO* [qtp1651286619-5931] log.request 10/Dec/2021:13:22:47 -0500 [73264] <- 200 application/json 28ms
10.12.2021 13:22:47.103 *INFO* [qtp1651286619-5931] log.access 54.209.162.6 - admin 10/Dec/2021:13:22:47 -0500 "POST /system/jackrabbit/filevault/rcp HTTP/1.1" 200 37 "http://qa-aem65-auth.corp.global:4502/etc/acs-tools/vlt-rcp.html" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.55 Safari/537.36"
10.12.2021 13:22:47.146 *INFO* [qtp1651286619-5931] log.request 10/Dec/2021:13:22:47 -0500 [73265] -> GET /system/jackrabbit/filevault/rcp?ck=1639160566959 HTTP/1.1
10.12.2021 13:22:47.148 *INFO* [qtp1651286619-5931] log.request 10/Dec/2021:13:22:47 -0500 [73265] <- 200 application/json 2ms
10.12.2021 13:22:47.148 *INFO* [qtp1651286619-5931] log.access 54.209.162.6 - admin 10/Dec/2021:13:22:47 -0500 "GET /system/jackrabbit/filevault/rcp?ck=1639160566959 HTTP/1.1" 200 9106 "http://qa-aem65-auth.corp.global:4502/etc/acs-tools/vlt-rcp.html" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.55 Safari/537.36"
10.12.2021 13:22:48.509 *ERROR* [Vault RCP Task - Norm1] org.apache.jackrabbit.spi2davex.RepositoryServiceImpl Internal error while retrieving NodeInfo for http://aem-assets-sandbox1-auth.corp.global:4502/crx/server/crx.default/jcr%3aroot/content/dam.
java.io.IOException: Error retrieving namespace uri
                at org.apache.jackrabbit.spi2davex.ItemInfoJsonHandler.key(ItemInfoJSONHandler.java:205) [org.apache.jackrabbit.vault.rcp:3.5.6]
                at org.apache.jackrabbit.commons.json.JsonParser.parse(JsonParser.java:108)
                at org.apache.jackrabbit.commons.json.JsonParser.parse(JsonParser.java:73)
                at org.apache.jackrabbit.spi2davex.RepositoryServiceImpl.getItemInfos(RepositoryServiceImpl.java:356) [org.apache.jackrabbit.vault.rcp:3.5.6]
                at org.apache.jackrabbit.jcr2spi.state.WorkspaceItemStateFactory.createNodeState(WorkspaceItemStateFactory.java:93) [org.apache.jackrabbit.vault.rcp:3.5.6]
                at org.apache.jackrabbit.jcr2spi.state.TransientISFactory.createNodeState(TransientISFactory.java:97) [org.apache.jackrabbit.vault.rcp:3.5.6]
                at org.apache.jackrabbit.jcr2spi.hierarchy.NodeEntryImpl.doResolve(NodeEntryImpl.java:990) [org.apache.jackrabbit.vault.rcp:3.5.6]
                at org.apache.jackrabbit.jcr2spi.hierarchy.HierarchyEntryImpl.resolve(HierarchyEntryImpl.java:134) [org.apache.jackrabbit.vault.rcp:3.5.6]
                at org.apache.jackrabbit.jcr2spi.hierarchy.HierarchyEntryImpl.getItemState(HierarchyEntryImpl.java:253) [org.apache.jackrabbit.vault.rcp:3.5.6]
                at org.apache.jackrabbit.jcr2spi.hierarchy.NodeEntryImpl.getItemState(NodeEntryImpl.java:71) [org.apache.jackrabbit.vault.rcp:3.5.6]
                at org.apache.jackrabbit.jcr2spi.hierarchy.NodeEntryImpl.getNodeState(NodeEntryImpl.java:363) [org.apache.jackrabbit.vault.rcp:3.5.6]
                at org.apache.jackrabbit.jcr2spi.state.ItemState.getParent(ItemState.java:213) [org.apache.jackrabbit.vault.rcp:3.5.6]
                at org.apache.jackrabbit.jcr2spi.state.NodeState.retrieveDefinition(NodeState.java:465) [org.apache.jackrabbit.vault.rcp:3.5.6]
                at org.apache.jackrabbit.jcr2spi.state.NodeState.getDefinition(NodeState.java:316) [org.apache.jackrabbit.vault.rcp:3.5.6]
                at org.apache.jackrabbit.jcr2spi.NodeImpl.getDefinition(NodeImpl.java:857) [org.apache.jackrabbit.vault.rcp:3.5.6]
                at org.apache.jackrabbit.vault.util.RepositoryCopier.copy(RepositoryCopier.java:315) [org.apache.jackrabbit.vault:3.2.8]
                at org.apache.jackrabbit.vault.util.RepositoryCopier.copy(RepositoryCopier.java:278) [org.apache.jackrabbit.vault:3.2.8]
                at org.apache.jackrabbit.vault.rcp.impl.RcpTaskImpl.run(RcpTaskImpl.java:277) [org.apache.jackrabbit.vault.rcp:3.5.6]
                at java.lang.Thread.run(Thread.java:748)
Caused by: javax.jcr.NamespaceException: Error retrieving namespace uri
                at org.apache.jackrabbit.spi2dav.RepositoryServiceImpl$NamespaceResolverImpl.getURI(RepositoryServiceImpl.java:3435) [org.apache.jackrabbit.vault.rcp:3.5.6]
                at org.apache.jackrabbit.spi.commons.conversion.NameParser.parse(NameParser.java:187)
                at org.apache.jackrabbit.spi.commons.conversion.ParsingNameResolver.getQName(ParsingNameResolver.java:64)
                at org.apache.jackrabbit.spi2dav.RepositoryServiceImpl$NamePathResolverImpl.getQName(RepositoryServiceImpl.java:3516) [org.apache.jackrabbit.vault.rcp:3.5.6]
                at org.apache.jackrabbit.spi2davex.ItemInfoJsonHandler.key(ItemInfoJSONHandler.java:201) [org.apache.jackrabbit.vault.rcp:3.5.6]
                ... 18 common frames omitted
Caused by: javax.jcr.NamespaceException: ns1: is not a registered namespace prefix.
                at org.apache.jackrabbit.spi2dav.RepositoryServiceImpl$NamespaceCache.getURI(RepositoryServiceImpl.java:3570) [org.apache.jackrabbit.vault.rcp:3.5.6]
                at org.apache.jackrabbit.spi2dav.RepositoryServiceImpl.getNamespaceURI(RepositoryServiceImpl.java:2658) [org.apache.jackrabbit.vault.rcp:3.5.6]
                at org.apache.jackrabbit.spi2dav.RepositoryServiceImpl$NamespaceResolverImpl.getURI(RepositoryServiceImpl.java:3432) [org.apache.jackrabbit.vault.rcp:3.5.6]
                ... 22 common frames omitted
10.12.2021 13:22:48.509 *ERROR* [Vault RCP Task - Norm1] org.apache.jackrabbit.vault.util.RepositoryCopier Error during copy: javax.jcr.RepositoryException: Error retrieving namespace uri

**Comment by kwin** [comment]
As ACS AEM Tools merely provides the UI, please rather report this issue at https://issues.apache.org/jira/projects/JCRVLT/issues which is the issue tracker for https://jackrabbit.apache.org/filevault/rcp.html#Vault_RCP_Server_Bundle (preferably including a package of the affected repositoy content at /jcr:root/content/dam.

**Comment by normraby** [comment]
Thanks for letting me know. I will open a ticket with them.



Norm Raby   | ROM Team Engineer
***@***.******@***.***> | Twitter<https://twitter.com/3SHARE> | LinkedIn<https://www.linkedin.com/company/1621497/> | Facebook<https://www.facebook.com/3share/>
[signature_1161522879][signature_2038275342]


From: Konrad Windszus ***@***.***>
Reply-To: Adobe-Consulting-Services/acs-aem-tools ***@***.***>
Date: Tuesday, January 4, 2022 at 1:56 PM
To: Adobe-Consulting-Services/acs-aem-tools ***@***.***>
Cc: ***@***.***" ***@***.***>, Author ***@***.***>
Subject: Re: [Adobe-Consulting-Services/acs-aem-tools] VLT-RCP Issues on AEM 6.5 (Issue #236)

This email has been sent from a source external to Publicis Groupe. Please use caution when clicking links or opening attachments.
Cet email a été envoyé depuis une source externe à Publicis Groupe. Veuillez faire preuve de prudence lorsque vous cliquez sur des liens ou lorsque vous ouvrez des pièces jointes.



As ACS AEM Tools merely provides the UI, please rather report this issue at https://issues.apache.org/jira/projects/JCRVLT/issues<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fissues.apache.org%2Fjira%2Fprojects%2FJCRVLT%2Fissues&data=04%7C01%7Cnormand.raby%403sharecorp.com%7C130ce6ca796848315c5308d9cfb3db8a%7Cd52c9ea17c2147b182a333a74b1f74b8%7C1%7C0%7C637769193660599113%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=yJ94%2BdlR0ZjybkR7c2drSe96aiRPYqiqDxb0cp0je5k%3D&reserved=0> which is the issue tracker for https://jackrabbit.apache.org/filevault/rcp.html#Vault_RCP_Server_Bundle<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fjackrabbit.apache.org%2Ffilevault%2Frcp.html%23Vault_RCP_Server_Bundle&data=04%7C01%7Cnormand.raby%403sharecorp.com%7C130ce6ca796848315c5308d9cfb3db8a%7Cd52c9ea17c2147b182a333a74b1f74b8%7C1%7C0%7C637769193660599113%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=7nXqIOvNFuFaAocn9Vq6HGpfzGYKnQHVGabkWa0SrFg%3D&reserved=0> (preferably including a package of the affected repositoy content at /jcr:root/content/dam.

—
Reply to this email directly, view it on GitHub<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAdobe-Consulting-Services%2Facs-aem-tools%2Fissues%2F236%23issuecomment-1005085252&data=04%7C01%7Cnormand.raby%403sharecorp.com%7C130ce6ca796848315c5308d9cfb3db8a%7Cd52c9ea17c2147b182a333a74b1f74b8%7C1%7C0%7C637769193660599113%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=DoirsPNA0DfCWa1zap4y8KX6tvl60k0BMpH6oTJgyto%3D&reserved=0>, or unsubscribe<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAGT6EUJMI3RTFHXHFC2CEITUUM7EHANCNFSM5KJAMZ2Q&data=04%7C01%7Cnormand.raby%403sharecorp.com%7C130ce6ca796848315c5308d9cfb3db8a%7Cd52c9ea17c2147b182a333a74b1f74b8%7C1%7C0%7C637769193660599113%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=dhmb0O%2F8ht8HDsWRQWYgn9pF1qsCuymLrn96Th7Nq3c%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cnormand.raby%403sharecorp.com%7C130ce6ca796848315c5308d9cfb3db8a%7Cd52c9ea17c2147b182a333a74b1f74b8%7C1%7C0%7C637769193660599113%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=rZU7PJSC0boLajtFyhhWKBZg1l6ZUWRPnOS1sv7WnYM%3D&reserved=0> or Android<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cnormand.raby%403sharecorp.com%7C130ce6ca796848315c5308d9cfb3db8a%7Cd52c9ea17c2147b182a333a74b1f74b8%7C1%7C0%7C637769193660599113%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=fX0i5ZhZGfyRF%2FmGcU4Q%2FS1LCMGC6KFyPtvrVefa%2FSc%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.***>




------------------------------------------------------------------------
Disclaimer The information in this email and any attachments may contain proprietary and confidential information that is intended for the addressee(s) only. If you are not the intended recipient, you are hereby notified that any disclosure, copying, distribution, retention or use of the contents of this information is prohibited. When addressed to our clients or vendors, any information contained in this e-mail or any attachments is subject to the terms and conditions in any governing contract. If you have received this e-mail in error, please immediately contact the sender and delete the e-mail.
