### ISSUE TITLE
Explain Query - TurboFilter; Performance considerations

### ISSUE THREAD

**Issue by davidjgonzalez** [Adobe-Consulting-Services/acs-aem-tools#98]
@chetanmeh was talking w @andrewmkhoury today and he had noticed that Explain Query's TurboFilter is present in *many* thread dumps. Just confirming that this check is fast and OK; not sure if you have insight into how fast is sufficiently fast for such a common extension point.

Per @andrewmkhoury - seems to get called whenever isDebugEnabled is called.

```
at java.lang.Thread.currentThread(Native Method)
    at java.lang.ThreadLocal.set(ThreadLocal.java:180)
    at ch.qos.logback.classic.util.LogbackMDCAdapter.getPropertyMap(LogbackMDCAdapter.java:161)
    at ch.qos.logback.classic.util.LogbackMDCAdapter.get(LogbackMDCAdapter.java:148)
    at org.slf4j.MDC.get(MDC.java:140)
    at com.adobe.acs.tools.explain_query.impl.ExplainQueryServlet$QueryLogCollector.decide(ExplainQueryServlet.java:396)
    at ch.qos.logback.classic.spi.TurboFilterList.getTurboFilterChainDecision(TurboFilterList.java:62)
    at ch.qos.logback.classic.LoggerContext.getTurboFilterChainDecision_0_3OrMore(LoggerContext.java:252)
    at ch.qos.logback.classic.Logger.callTurboFilters(Logger.java:772)
    at ch.qos.logback.classic.Logger.isDebugEnabled(Logger.java:490)
    at ch.qos.logback.classic.Logger.isDebugEnabled(Logger.java:486)
    at org.apache.jackrabbit.oak.util.PerfLogger.start(PerfLogger.java:66)
    at org.apache.jackrabbit.oak.plugins.document.mongo.MongoDocumentStore.find(MongoDocumentStore.java:320)
```

**Comment by justinedelson** [comment]
Given that this is for dev environments only, I don't think this is a big deal.

**Comment by davidjgonzalez** [comment]
@justinedelson i tend to agree, but the reality is a lot of folks are using ACS Tools (specifically Explain Query) on Prod these days. If we can (easily) make this less intrusive, i'm be supportive of it.

**Comment by justinedelson** [comment]
So how would we do that? Or is this just a matter of creating an issue to
track the performance investigation?

**Comment by davidjgonzalez** [comment]
@justinedelson I believe the above is sufficient but would like to get @chetanmeh's point of view as he has more experience w Logback/TurboFilter than I. If you know this is a non-issue, i'm happy to close.

Basically i'm asking the question as I'm unsure. I've learned that when @andrewmkhoury asks a question I cant answer, its usually a good idea to figure out what the answer is :)

**Comment by davidjgonzalez** [comment]
Fixed in master
